FROM amd64/python:3.8-slim-buster

WORKDIR /app

RUN apt-get update
RUN apt-get install -y iproute2

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]